name: Main Workflow

# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
    paths:
      - '**.java'
      - '**.groovy'
      - '**.ts'
      - '**.yaml'
      - '**.xml'

jobs:
  build:
    # Job name is verify
    name: Run
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Branch name
        run: echo running on branch ${GITHUB_REF}

      - name: Setup java 11
        uses: actions/setup-java@v1
        with:
          version: '11.0.5'
          architecture: x64

      - name: Check java version
        run: java --version

      - name: Check maven version
        run: mvn -version

      - name: maven verify
        run: mvn -U clean verify
